# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/nomasters/hashmap
    steps:
      - run: sudo apt-get update && sudo apt-get install clang
      - checkout
      - run: ./scripts/build.sh
      - run: go test -race -v ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global