# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/nomasters/hashmap
    steps:
      - run: sudo apt-get update && sudo apt-get install clang
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -u golang.org/x/vgo
      - run: vgo get -v -d ./...
      - run: vgo test -v ./...
      - run: vgo test -race -coverprofile=coverage.txt -covermode=atomic
      # - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global